name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch (modify as needed)

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger GitLab CI pipeline for main branch
        run: |
          curl --request POST \
               --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
               --form "ref=main" \
               "https://gitlab.com/api/v4/projects/3dverse/showcase/microverses/livelink-app-template/trigger/pipeline"
               - name: Trigger GitLab pipeline for prod branch
      - name: Trigger GitLab CI pipeline for prod branch
        run: |
          curl --request POST \
               --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
               --form "ref=prod" \
               "https://gitlab.com/api/v4/projects/3dverse/showcase/microverses/livelink-app-template/trigger/pipeline"